---
- hosts: localhost
  tasks:
  - name: Upload html
    aws_s3:
      bucket: project-devops-frontend-gcm
      object: index.html
      src: "file_s3/index.html"
      mode: put
  - name: Upload image
    aws_s3:
      bucket: project-devops-frontend-gcm
      object: projectdevops.png
      src: "file_s3/projectdevops.png"
      mode: put

#run
##ansible-playbook -i hosts s3_bucket.yaml
